openapi: 3.0.4
info:
  title: Lunch & Learn – Swagger in .NET 9
  description: This API demonstrates how to enable and explore Swagger UI in .NET 9. It’s part of a Lunch & Learn session covering Swagger (OpenAPI) setup, interactive documentation, and built-in OpenAPI integration.
  version: v1
paths:
  /WeatherForecast:
    get:
      tags:
        - WeatherForecast
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WeatherForecast'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WeatherForecast'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WeatherForecast'
    post:
      tags:
        - WeatherForecast
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WeatherForecast'
          text/json:
            schema:
              $ref: '#/components/schemas/WeatherForecast'
          application/*+json:
            schema:
              $ref: '#/components/schemas/WeatherForecast'
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/WeatherForecast'
            application/json:
              schema:
                $ref: '#/components/schemas/WeatherForecast'
            text/json:
              schema:
                $ref: '#/components/schemas/WeatherForecast'
  /WeatherForecast/{id}:
    get:
      tags:
        - WeatherForecast
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/WeatherForecast'
            application/json:
              schema:
                $ref: '#/components/schemas/WeatherForecast'
            text/json:
              schema:
                $ref: '#/components/schemas/WeatherForecast'
    put:
      tags:
        - WeatherForecast
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WeatherForecast'
          text/json:
            schema:
              $ref: '#/components/schemas/WeatherForecast'
          application/*+json:
            schema:
              $ref: '#/components/schemas/WeatherForecast'
      responses:
        '200':
          description: OK
    delete:
      tags:
        - WeatherForecast
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
components:
  schemas:
    WeatherForecast:
      type: object
      properties:
        date:
          type: string
          format: date
        temperatureC:
          type: integer
          format: int32
        temperatureF:
          type: integer
          format: int32
          readOnly: true
        summary:
          type: string
          nullable: true
      additionalProperties: false
