apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: weather-forecast-api
  description: Weather Forecast API (.NET 8 Swagger)
spec:
  type: openapi
  lifecycle: development
  owner: demo-team
  definition:
    $text: https://configapi.dev.cordellacare.com/swagger/v1/swagger.json

